### ISSUE TITLE
Ethnicity has UI default but shows warning that field is required

### ISSUE THREAD

**Issue by mmazanec22** [ctoec/ecis-experimental#510] opened 2019-12-30 18:37 UTC
![Screenshot from 2019-12-30 13-37-00](https://user-images.githubusercontent.com/12260067/71595420-88520c80-2b09-11ea-81b4-b42801b6ef87.png)

**Comment by cailyncodes** [comment] 2019-12-30 18:39
This looks like there was a regression of https://github.com/ctoec/ecis-experimental/issues/413

**Comment by abbyraskin** [comment] 2020-01-03 20:26
closing in favor of https://github.com/ctoec/ecis-experimental/issues/542

**Closed by abbyraskin** 2020-01-03 20:26 UTC
Labels: bug
