### ISSUE TITLE
Adding new family income determination puts the newly created determination as the past and the old one as "New"

### ISSUE THREAD

**Issue by victoriasuwardiman** [ctoec/ecis-experimental#997] opened 2020-04-27 18:39 UTC
1. Go to a child's summary page
2. Update Family Income Determination
3. Add new income determination
4. The newly created income determination is in a gray box below and the old one has the New tag

![image](https://user-images.githubusercontent.com/51121888/80408178-c3383700-8894-11ea-8f71-08f711023978.png)

**Comment by cailyncodes** [comment] 2020-04-27 18:43
What dates were in the "old" one and what date was entered for the newly added one?

**Comment by cailyncodes** [comment] 2020-04-27 19:41
Closing as not a bug

**Closed by cailyncodes** 2020-04-27 19:41 UTC
Labels: bug
